"""Vendored Bambu HMS catalog: fault text + wiki deep links.

Pure data module — no imports from ``hms_errors`` (which imports THIS). The two
gzip JSON files are generated by ``scripts/update_hms_errors.py`` from Bambu's
official ``e.bambulab.com/query.php`` catalog and ``wiki.bambulab.com`` HMS pages.

Keys are Bambu ``ecode`` values, uppercased. Text keys are length-disjoint (16
hex for ``device_hms`` faults = attr<<32|code, 8 hex for ``device_error`` faults)
so one flat dict is unambiguous and matches the ``full_code`` the MQTT parser
builds. Wiki keys are always the 16-hex form.

Loaded eagerly at import — the precedent is ``hms_actions.py``. Absolute paths
keep the load independent of CWD (systemd unit, Docker entrypoint, pytest).
"""

import gzip
import json
from pathlib import Path

_DATA_DIR = Path(__file__).resolve().parent.parent / "data"
_TEXT_FILE = _DATA_DIR / "hms_error_text_en.json.gz"
_WIKI_FILE = _DATA_DIR / "hms_wiki_links_en.json.gz"


def _load(path: Path) -> dict[str, str]:
    """Load a gzip JSON dict, upper-casing keys. Missing file -> empty dict."""
    if not path.exists():
        return {}
    with gzip.open(path, "rb") as f:
        raw = json.loads(f.read().decode("utf-8"))
    return {str(k).upper(): v for k, v in raw.items()}


_ERROR_TEXT: dict[str, str] = _load(_TEXT_FILE)
_WIKI_LINKS: dict[str, str] = _load(_WIKI_FILE)


def lookup_full_code(full_code: str | None) -> str | None:
    """Return the vendor fault text for a full ``ecode`` (16- or 8-hex), or None.

    Case-insensitive; tolerates empty/None input.
    """
    if not full_code:
        return None
    return _ERROR_TEXT.get(str(full_code).upper())


def lookup_wiki_path(full_code: str | None) -> str | None:
    """Return the wiki troubleshooting deep-link PATH for a code, or None.

    The path is site-relative (e.g. ``/en/x1/troubleshooting/hmscode/...``);
    callers prepend the wiki origin. Case-insensitive; tolerates empty/None.
    """
    if not full_code:
        return None
    return _WIKI_LINKS.get(str(full_code).upper())
