"""Tests for the vendored HMS catalog (fault text + wiki deep links).

The data files are generated by ``scripts/update_hms_errors.py`` from Bambu's
official ``e.bambulab.com/query.php`` catalog. These tests assert the loader and
lookups behave against the shipped data.
"""

from backend.app.services import hms_catalog
from backend.app.services.hms_catalog import lookup_full_code, lookup_wiki_path

# The MicroSD "not enough space" fault the live fleet reports (attr 0x05000100,
# code 0x00030004 → full_code 0500010000030004). Its text + deep link are the
# canonical acceptance case for this feature.
_TARGET = "0500010000030004"
# An 8-hex device_error key with a hex letter — exercises the 8/16-hex disjoint
# key space and case-insensitivity.
_EIGHT_HEX = "0500806E"


class TestErrorTextLoad:
    def test_catalog_loaded_non_empty(self):
        assert len(hms_catalog._ERROR_TEXT) > 1000

    def test_target_16hex_resolves_microsd_text(self):
        text = lookup_full_code(_TARGET)
        assert text is not None
        assert "Not enough space" in text

    def test_eight_hex_device_error_key_hits(self):
        text = lookup_full_code(_EIGHT_HEX)
        assert text is not None
        assert "Foreign objects" in text

    def test_unknown_full_code_returns_none(self):
        assert lookup_full_code("FFFFFFFFFFFFFFFF") is None

    def test_case_insensitive_key(self):
        assert lookup_full_code(_EIGHT_HEX.lower()) == lookup_full_code(_EIGHT_HEX)

    def test_empty_and_none_tolerated(self):
        assert lookup_full_code("") is None
        assert lookup_full_code(None) is None


class TestWikiLinks:
    def test_wiki_catalog_loaded_non_empty(self):
        assert len(hms_catalog._WIKI_LINKS) > 0

    def test_target_has_deep_link(self):
        path = lookup_wiki_path(_TARGET)
        assert path is not None
        assert "/hmscode/" in path
        assert path.startswith("/en/")

    def test_unknown_wiki_returns_none(self):
        assert lookup_wiki_path("FFFFFFFFFFFFFFFF") is None

    def test_wiki_empty_and_none_tolerated(self):
        assert lookup_wiki_path("") is None
        assert lookup_wiki_path(None) is None
